// ═══════════════════════════════════════════════════════════════
//  data-content.js — 网页框架文字 & UI 标签 & 语录
//  Website framework text, UI labels & quotes.
//  修改此文件即可修改页面上所有静态文字。
// ═══════════════════════════════════════════════════════════════
window.SITE_TEXT = {

  // ─── 翻译 (data-i18n 对应的中英文) ───
  translations: {
    'nav-hero':{cn:'关于',en:'About'},'nav-interest':{cn:'兴趣',en:'Interests'},'nav-career':{cn:'工作',en:'Career'},'nav-study':{cn:'学习',en:'Learning'},'nav-worldmap':{cn:'足迹',en:'Footprints'},'nav-timelines':{cn:'经历',en:'Experience'},'nav-skills':{cn:'技能',en:'Skills'},'nav-takeaway':{cn:'联系',en:'Contact'},
    'hero-title':{cn:'欢迎来到小对的星空',en:'Welcome to XD\'s Starry Sky'},
    'hero-hint':{cn:'<span class="rules-action">点击星星了解更多</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">探索 3 颗不同词可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Tap the stars to learn more</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Discover 3 different ones to earn a star <span class="rule-star">✦</span></span>'},
    'intro-star-hero':{cn:'<span class="rule-star">✦</span> 探索 3 颗不同的星星关键词',en:'<span class="rule-star">✦</span> Explore 3 different star keywords'},
    'intro-star-interest':{cn:'<span class="rule-star">✦</span> 翻开全部卡片完成配对',en:'<span class="rule-star">✦</span> Match all card pairs'},
    'intro-star-career':{cn:'<span class="rule-star">✦</span> 前往 3 个楼层并分别点开 1 个显示屏',en:'<span class="rule-star">✦</span> Visit all 3 floors and open one monitor on each'},
    'intro-star-study':{cn:'<span class="rule-star">✦</span> 戳开 5 个知识泡泡',en:'<span class="rule-star">✦</span> Pop 5 knowledge bubbles'},
    'intro-star-worldmap':{cn:'<span class="rule-star">✦</span> 展开 2 张卷轴地图',en:'<span class="rule-star">✦</span> Unroll both scroll maps'},
    'intro-star-timelines':{cn:'<span class="rule-star">✦</span> 拖动钟楼转圈 5 个标签都看过',en:'<span class="rule-star">✦</span> Spin the clock tower and view all 5 categories'},
    'intro-star-skills':{cn:'<span class="rule-star">✦</span> 走遍 6 片花丛查看技能',en:'<span class="rule-star">✦</span> Visit all 6 flower beds to view skills'},
    'intro-star-ending':{cn:'<span class="rule-star">✦</span> 点击查看 收集最后 1 颗星星',en:'<span class="rule-star">✦</span> Tap to collect the final star'},
    'scroll-hint':{cn:'向下滑动',en:'Scroll down'},
    'dismiss-click':{cn:'点击任意处关闭',en:'Click anywhere to close'},
    'interest-welcome':{cn:'欢迎来到兴趣游乐场',en:'Welcome to the Hobby Playground'},
    'interest-desc':{cn:'了解一个人，从TA的兴趣开始<br>翻翻卡片，看看小对藏了哪些宝藏爱好',en:'The best way to know someone is through their hobbies<br>Flip the cards to discover XD\'s hidden interests'},
    'interest-title':{cn:'兴趣对对碰',en:'Hobby Match'},
    'interest-rules':{cn:'<span class="rules-action">翻开两张同类卡片即可配对，点击「打乱重来」可重新开始</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">全部配对完成可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Flip two cards of the same category to match. Click "Shuffle" to restart</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Match all cards to earn a star <span class="rule-star">✦</span></span>'},
    'interest-rules-html':{cn:'<span class="rules-action">翻开两张同类卡片即可配对，点击「<a class="shuffle-link" href="#">打乱重来</a>」可重新开始</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">全部配对完成可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Flip two cards of the same category to match. Click "<a class="shuffle-link" href="#">Shuffle</a>" to restart</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Match all cards to earn a star <span class="rule-star">✦</span></span>'},
    'shuffle-btn':{cn:'打乱重来',en:'Shuffle'},
    'game-hint':{cn:'翻开两张同类卡片试试看！',en:'Try flipping two cards of the same type!'},
    'career-welcome':{cn:'欢迎来到事业大楼',en:'Welcome to the Career Building'},
    'career-desc':{cn:'坐电梯上楼<br>走进小对的 3 个工作房间',en:'Take the elevator upstairs<br>Step into XD\'s three work rooms'},
    'career-title':{cn:'我的经历',en:'My Experience'},
    'career-elevator':{cn:'电梯',en:'ELEVATOR'},
    'career-rules':{cn:'<span class="rules-action">乘坐电梯前往不同的楼层</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">每层点开 1 个显示屏可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Take the elevator to explore each floor</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Open one monitor per floor to earn a star <span class="rule-star">✦</span></span>'},
    'study-welcome':{cn:'欢迎来到知识湖',en:'Welcome to the Knowledge Lake'},
    'study-desc':{cn:'知识湖里漂浮着许多泡泡<br>戳开一个，学习一个新词汇吧',en:'The Knowledge Lake is filled with bubbles<br>Pop one to learn a new term'},
    'study-title':{cn:'知识泡泡',en:'Knowledge Bubbles'},
    'study-rules':{cn:'<span class="rules-action">戳开湖里的泡泡学新词汇</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">戳开 5 个泡泡可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Pop bubbles to learn new terms</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Pop 5 bubbles to earn a star <span class="rule-star">✦</span></span>'},
    'bubble-hint':{cn:'戳开泡泡试试看',en:'Try popping a bubble'},
    'worldmap-welcome':{cn:'欢迎来到故事杂货铺',en:'Welcome to the Story Bazaar'},
    'worldmap-desc':{cn:'这里是一间只卖故事的小店<br>柜台上的地图藏着小对走过的地方',en:'A tiny shop that only sells stories<br>The maps on the counter hold XD\'s footprints'},
    'worldmap-title':{cn:'故事杂货铺',en:'Story Bazaar'},
    'worldmap-rules':{cn:'<span class="rules-action">探索地图与杂货铺</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">2 张地图都打开可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Explore the maps and bazaar shelves</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Open both maps to earn a star <span class="rule-star">✦</span></span>'},
    'story-shop-sign':{cn:'小对故事杂货铺',en:'XD Story Bazaar'},
    'shop-album-title':{cn:'贝多芬第九交响曲',en:'Beethoven Symphony No. 9'},
    'shop-album-desc':{cn:'这是小对最喜欢的专辑',en:'XD\'s favorite album'},
    'shop-violin-title':{cn:'小提琴谱',en:'Violin Score'},
    'shop-piano-title':{cn:'钢琴谱',en:'Piano Score'},
    'shop-choir-title':{cn:'合唱谱',en:'Choir Score'},
    'shop-score-desc':{cn:'小对曾经认真练习过的技能',en:'A skill XD once practiced seriously'},
    'shop-bike-title':{cn:'公路车模型',en:'Road Bike Model'},
    'shop-bike-desc':{cn:'小对的运动爱好纪念品',en:'A keepsake for XD\'s sports hobby'},
    'shop-puppy-title':{cn:'线条小狗玩偶',en:'Line Puppy Plush'},
    'shop-puppy-desc':{cn:'小对最喜欢的 IP',en:'XD\'s favorite character IP'},
    'shop-coffee-title':{cn:'美式咖啡',en:'Americano'},
    'shop-coffee-desc':{cn:'小对最喜欢的饮品（广告位招租）',en:'XD\'s favorite drink (ad slot open)'},
    'shop-snack-title':{cn:'薯片 / 零食',en:'Chips / Snacks'},
    'shop-snack-desc':{cn:'小对最喜欢的零食（广告位招租）',en:'XD\'s favorite snack (ad slot open)'},
    'story-map-china':{cn:'中国地图',en:'China Map'},
    'story-map-china-desc':{cn:'家乡、大学、旅行和短居，都夹在这张地图里',en:'Hometown, university, trips, and short stays live in this map'},
    'story-map-world':{cn:'世界地图',en:'World Map'},
    'story-map-world-desc':{cn:'交换、远行和语言故事，摊开就是一整个世界',en:'Exchange, journeys, and language stories unfold across the world'},
    'story-map-title':{cn:'地图摊开了',en:'The map is open'},
    'story-map-title-china':{cn:'中国地图摊开了',en:'China map is open'},
    'story-map-title-world':{cn:'世界地图摊开了',en:'World map is open'},
    'map-visit':{cn:'我去过',en:'Visited'},'map-lang':{cn:'我会说这里的语言',en:'Language-learned'},
    'map-transit':{cn:'途经',en:'Transit'},'map-travel':{cn:'旅行',en:'Travel'},'map-short':{cn:'短居',en:'Stay'},'map-long':{cn:'长住',en:'Live'},
    'map-beginner':{cn:'入门',en:'Beginner'},'map-proficient':{cn:'熟练',en:'Proficient'},'map-fluent':{cn:'精通',en:'Fluent'},'map-native':{cn:'母语',en:'Native'},
    'map-instr':{cn:'点击标记切换 · 滚轮缩放 · 拖拽平移',en:'Click to toggle · Scroll to zoom · Drag to pan'},
    'timelines-welcome':{cn:'欢迎来到经历钟楼',en:'Welcome to the Experience Clock Tower'},
    'timelines-desc':{cn:'每一段经历都值得被记住<br>跟着时间轴，回顾小对的成长足迹',en:'Every experience is worth remembering<br>Follow the timeline to trace XD\'s growth'},
    'timelines-title':{cn:'时间轴',en:'Timeline'},
    'timelines-rules':{cn:'<span class="rules-action">拖动钟楼或点击标签切换</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">浏览全部 5 类经历可获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Drag the clock tower or tap tabs</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">View all 5 categories to earn a star <span class="rule-star">✦</span></span>'},
    'tl-edu':{cn:'学业',en:'Education'},'tl-work':{cn:'工作',en:'Work'},'tl-proj':{cn:'项目',en:'Projects'},'tl-culture':{cn:'文化',en:'Culture'},'tl-honor':{cn:'荣誉',en:'Honors'},
    'tl-hint':{cn:'点击上方标签可显示/隐藏对应内容',en:'Click a label above to show/hide its entries'},
    'skills-welcome':{cn:'欢迎来到技能花园',en:'Welcome to the Skill Garden'},
    'skills-desc':{cn:'每一片叶子都是一项技能<br>一起看看小对的技能全景图',en:'Every leaf represents a skill<br>Explore XD\'s full skill panorama'},
    'skills-title':{cn:'技能花园',en:'Skill Garden'},
    'skills-rules':{cn:'<span class="rules-action">方向键/WASD 移动 · 靠近花丛查看技能</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">走过 6 片花丛后获得星星 <span class="rule-star">✦</span></span>',en:'<span class="rules-action">Use arrows / WASD to move · Walk near flower beds to view skills</span><span class="rules-star-sep"> · </span><br class="rules-star-br"><span class="rules-star-line">Visit all 6 flower beds to earn a star <span class="rule-star">✦</span></span>'},
    'takeaway-welcome':{cn:'感谢你的探索',en:'Thanks for exploring'},
    'takeaway-desc':{cn:'还没看够？快来联系我！<br>线上沟通、线下 Coffee Chat 都很欢迎',en:'Want to know more? Reach out!<br>Online or offline Coffee Chat — all welcome'},
    'takeaway-title':{cn:'联系方式',en:'Contact'},
    'contact-tel':{cn:'电话',en:'Phone'},'contact-email':{cn:'邮箱',en:'Email'},'contact-wechat':{cn:'微信',en:'WeChat'},'contact-red':{cn:'小红书',en:'RED'},'contact-linkedin':{cn:'领英',en:'LinkedIn'},'contact-strava':{cn:'Strava',en:'Strava'},
    'ending-label':{cn:'不知不觉就到最后啦<br>请查看小对给你的最后一个惊喜',en:'Before you know it, we\'re at the end<br>Check out XD\'s last surprise for you'},
    'quote-trigger':{cn:'点击查看',en:'Tap to collect'},
    'replay-btn':{cn:'再玩一次',en:'Play again'},
    'danmaku-settings':{cn:'弹幕设置',en:'Danmaku'},
    'danmaku-range':{cn:'区域',en:'Area'},
    'danmaku-range-full':{cn:'全屏',en:'Full'},
    'danmaku-speed':{cn:'速度',en:'Speed'},
    'danmaku-speed-slow':{cn:'慢',en:'Slow'},
    'danmaku-speed-normal':{cn:'中',en:'Medium'},
    'danmaku-speed-fast':{cn:'快',en:'Fast'},
    'danmaku-opacity':{cn:'透明',en:'Opacity'},
    'danmaku-name-label':{cn:'昵称',en:'Name'},
    'danmaku-name-placeholder':{cn:'昵称',en:'Name'},
    'danmaku-message-placeholder':{cn:'你也想和小对互动吗？请在这里留下你的弹幕吧',en:'Want to say hi to XD? Leave your danmaku here.'},
    'danmaku-message-placeholder-short':{cn:'在这里留下你的弹幕吧',en:'Leave a danmaku here'},
    'danmaku-send':{cn:'发送',en:'Send'},
    'danmaku-error-empty':{cn:'先写一点弹幕吧',en:'Write a danmaku first'},
    'danmaku-error-long':{cn:'内容太长啦，请控制在 80 字以内',en:'Keep it within 80 characters'},
    'danmaku-error-civil':{cn:'请文明用语，换一种更友好的说法吧',en:'Please keep it friendly and try another wording'},
    'danmaku-error-network':{cn:'暂时没连上云端，已先保存在本机',en:'Could not reach cloud storage, saved locally for now'},
    'unlock-congrats':{cn:'恭喜你解锁新场景',en:'You\'ve unlocked a new scene'},
    'unlock-dismiss':{cn:'点击任意处继续',en:'Click anywhere to continue'},
    'completion-title':{cn:'恭喜你顺利通关！',en:'Congratulations!'},
    'completion-p1':{cn:'认识小对的小游戏到这里就结束啦，',en:'The adventure of getting to know XD ends here,'},
    'completion-p2':{cn:'但小对和你的故事才刚刚开始，',en:'but XD\'s story with you is just beginning,'},
    'completion-p3':{cn:'让我们一起继续探索吧，',en:'let\'s keep exploring together,'},
    'completion-p4':{cn:'相信她一定会给你带来惊喜！',en:'she\'s sure to surprise you!'},
    'quote-prev':{cn:'上一句',en:'Prev'},'quote-next':{cn:'换一句',en:'Next'},'quote-close':{cn:'点击空白处关闭',en:'Click outside to close'},
    'map-title':{cn:'— 探索路线图 —',en:'— EXPLORATION MAP —'},
    'star-map-title':{cn:'星星收集地图',en:'STAR COLLECTION MAP'},
    'star-map-earned':{cn:'已获得',en:'Collected'},
    'star-map-missing':{cn:'未获得',en:'Not yet'},
    'map-locked':{cn:'还没走到这里，先把前面的站点逛完吧',en:'You haven\'t reached this stop yet — keep exploring forward'},
    'map-b-hero':{cn:'关键词影院',en:'Keyword Cinema'},'map-b-interest':{cn:'兴趣游乐场',en:'Hobby Playground'},'map-b-career':{cn:'事业大楼',en:'Career Building'},'map-b-study':{cn:'知识湖',en:'Knowledge Lake'},'map-b-worldmap':{cn:'故事杂货铺',en:'Story Bazaar'},'map-b-timelines':{cn:'经历钟楼',en:'Experience Clock Tower'},'map-b-skills':{cn:'技能花园',en:'Skill Garden'},'map-b-takeaway':{cn:'邮局',en:'Post Office'},'map-b-ending':{cn:'终点',en:'Finish'}
  },

  // ─── XD送你的一句话 (20句，中英双语) ───
  quotes: [
    {cn:'不要把任何事视为理所当然。',en:'Never take anything for granted.'},
    {cn:'相信复利的力量。',en:'Believe in the power of compounding.'},
    {cn:'多看事实，少看观点。',en:'Focus on facts, not opinions.'},
    {cn:'观点会过时，能力不会。',en:'Opinions fade; abilities endure.'},
    {cn:'无所求必满载而归。',en:'Expect nothing, and you\'ll return with everything.'},
    {cn:'保持节奏，慌乱下一定成不了事。',en:'Keep your rhythm — nothing great is done in a rush.'},
    {cn:'着眼未来。',en:'Keep your eyes on the horizon.'},
    {cn:'慢慢来就是最快的。',en:'Go slow to go fast.'},
    {cn:'做人就像做游戏，做个有意思的人。',en:'Life is like a game — make yourself an interesting character.'},
    {cn:'乱了节奏也没关系，继续跳你的探戈吧。',en:'If you got tangled up, just tango on.'},
    {cn:'上帝给你关上一扇门，那就把它打开。因为门就是这样用的。',en:'When God closes a door, open it back up. That\'s how doors work.'},
    {cn:'允许一切发生。',en:'Let everything happen.'},
    {cn:'如果生活给你柠檬，那就做成柠檬水，再加点伏特加。',en:'When life gives you lemons, make lemonade — and add some vodka.'},
    {cn:'先完成，再完美。',en:'Done first, perfect later.'},
    {cn:'行动比情绪可靠。',en:'Action is more reliable than emotion.'},
    {cn:'做自己，因为别人都有人做了。',en:'Be yourself; everyone else is already taken.'},
    {cn:'简历是扁平的经历，但我是一个立体的人。',en:'A résumé is flat, but I am three-dimensional.'},
    {cn:'不要因为走了太远，而忘记我们为什么出发。',en:'Don\'t go so far that you forget why you set out.'},
    {cn:'每个人都有自己的时区。',en:'Everyone has their own timezone.'},
    {cn:'允许自己慢一点，但永远不要停下来。',en:'Allow yourself to go slow, but never stop.'}
  ]
};
